import os
import json
import asyncio
from openai import OpenAI
from dotenv import load_dotenv
from client import ResumeEnv
from models import ResumeAction

# Load environment variables from .env file
load_dotenv()

async def main():
    # 1. Read configuration from environment variables
    api_base_url = os.getenv("API_BASE_URL", "http://localhost:8000")
    model_name = os.getenv("MODEL_NAME", "gpt-4o")
    openai_api_key = os.getenv("OPENAI_API_KEY")

    # 2. Initialize env and OpenAI client
    # We use OpenAI client but calling it within an async function works fine
    client = OpenAI(api_key=openai_api_key)
    env = ResumeEnv(base_url=api_base_url)

    total_reward_all_episodes = 0.0
    num_episodes = 5

    print(f"Starting evaluation for {num_episodes} episodes...")

    # 3. Execution Flow: Loop for 5 episodes
    for i in range(num_episodes):
        print(f"\n--- Episode {i+1} ---")
        
        # 4. Call env.reset() to get observation
        observation = await env.reset()
        
        # 5. Build prompt
        prompt = f"""
        You are a recruitment specialist. Evaluate the following resume against the job description.
        
        Job Description:
        {observation.job_description}
        
        Resume Text:
        {observation.resume_text}
        
        Provide your decision in JSON format:
        - decision: "accept" or "reject"
        - fraud_flag: true or false
        - confidence: a value between 0 and 1
        """

        # 6. Dummy Policy (Fallback)
        fallback_action_dict = {
            "decision": "reject",
            "fraud_flag": False,
            "confidence": 0.6
        }

        action_dict = None

        # 7. Try to call OpenAI API
        try:
            # Check if key is available before calling
            if not openai_api_key or "your_api_key" in openai_api_key:
                raise ValueError("OpenAI API Key is missing or invalid.")

            response = client.chat.completions.create(
                model=model_name,
                messages=[{"role": "user", "content": prompt}],
                top_p=1,
                frequency_penalty=0,
                presence_penalty=0,
                response_format={"type": "json_object"}
            )
            
            # 8. OpenAI Response Handling & Safe Parsing
            content = json.loads(response.choices[0].message.content)
            
            # 9. Validation
            decision = content.get("decision")
            confidence = content.get("confidence")
            fraud_flag = content.get("fraud_flag")

            if (decision in ["accept", "reject"] and 
                isinstance(confidence, (int, float)) and 0.0 <= confidence <= 1.0 and
                isinstance(fraud_flag, bool)):
                action_dict = content
                print("Action successfully generated by OpenAI.")
            else:
                print("Invalid OpenAI response format. Falling back to dummy policy.")
                action_dict = fallback_action_dict
                
        except Exception as e:
            # 10. Fallback mechanism for ANY reason (quota, network, invalid key)
            print("Using fallback policy.")
            action_dict = fallback_action_dict

        # 11. Create ResumeAction and call env.step()
        action = ResumeAction(
            decision=action_dict["decision"],
            fraud_flag=action_dict["fraud_flag"],
            confidence=action_dict["confidence"]
        )

        observation = await env.step(action)
        reward = observation.reward
        done = observation.done
        
        # 12. Accumulate total reward
        total_reward_all_episodes += reward
        print(f"Episode Reward: {reward:.2f}")

    # 13. Print final results
    average_reward = total_reward_all_episodes / num_episodes
    print(f"\n==========================")
    print(f"Total Reward (5 Episodes): {total_reward_all_episodes:.2f}")
    print(f"Average Reward:          {average_reward:.2f}")
    print(f"==========================\n")

if __name__ == "__main__":
    asyncio.run(main())
